/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as ApiWarehousesRouteImport } from './routes/api/warehouses'
import { Route as ApiReservationsRouteImport } from './routes/api/reservations'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ApiReservationsIdRouteImport } from './routes/api/reservations.$id'
import { Route as ApiPublicExpireReservationsRouteImport } from './routes/api/public/expire-reservations'
import { Route as ApiReservationsIdReleaseRouteImport } from './routes/api/reservations.$id.release'
import { Route as ApiReservationsIdConfirmRouteImport } from './routes/api/reservations.$id.confirm'

const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWarehousesRoute = ApiWarehousesRouteImport.update({
  id: '/api/warehouses',
  path: '/api/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReservationsRoute = ApiReservationsRouteImport.update({
  id: '/api/reservations',
  path: '/api/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReservationsIdRoute = ApiReservationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiReservationsRoute,
} as any)
const ApiPublicExpireReservationsRoute =
  ApiPublicExpireReservationsRouteImport.update({
    id: '/api/public/expire-reservations',
    path: '/api/public/expire-reservations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReservationsIdReleaseRoute =
  ApiReservationsIdReleaseRouteImport.update({
    id: '/release',
    path: '/release',
    getParentRoute: () => ApiReservationsIdRoute,
  } as any)
const ApiReservationsIdConfirmRoute =
  ApiReservationsIdConfirmRouteImport.update({
    id: '/confirm',
    path: '/confirm',
    getParentRoute: () => ApiReservationsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/inventory': typeof InventoryRoute
  '/api/products': typeof ApiProductsRoute
  '/api/reservations': typeof ApiReservationsRouteWithChildren
  '/api/warehouses': typeof ApiWarehousesRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/api/public/expire-reservations': typeof ApiPublicExpireReservationsRoute
  '/api/reservations/$id': typeof ApiReservationsIdRouteWithChildren
  '/api/reservations/$id/confirm': typeof ApiReservationsIdConfirmRoute
  '/api/reservations/$id/release': typeof ApiReservationsIdReleaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/inventory': typeof InventoryRoute
  '/api/products': typeof ApiProductsRoute
  '/api/reservations': typeof ApiReservationsRouteWithChildren
  '/api/warehouses': typeof ApiWarehousesRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/api/public/expire-reservations': typeof ApiPublicExpireReservationsRoute
  '/api/reservations/$id': typeof ApiReservationsIdRouteWithChildren
  '/api/reservations/$id/confirm': typeof ApiReservationsIdConfirmRoute
  '/api/reservations/$id/release': typeof ApiReservationsIdReleaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/inventory': typeof InventoryRoute
  '/api/products': typeof ApiProductsRoute
  '/api/reservations': typeof ApiReservationsRouteWithChildren
  '/api/warehouses': typeof ApiWarehousesRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/api/public/expire-reservations': typeof ApiPublicExpireReservationsRoute
  '/api/reservations/$id': typeof ApiReservationsIdRouteWithChildren
  '/api/reservations/$id/confirm': typeof ApiReservationsIdConfirmRoute
  '/api/reservations/$id/release': typeof ApiReservationsIdReleaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/inventory'
    | '/api/products'
    | '/api/reservations'
    | '/api/warehouses'
    | '/checkout/$id'
    | '/api/public/expire-reservations'
    | '/api/reservations/$id'
    | '/api/reservations/$id/confirm'
    | '/api/reservations/$id/release'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/inventory'
    | '/api/products'
    | '/api/reservations'
    | '/api/warehouses'
    | '/checkout/$id'
    | '/api/public/expire-reservations'
    | '/api/reservations/$id'
    | '/api/reservations/$id/confirm'
    | '/api/reservations/$id/release'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/inventory'
    | '/api/products'
    | '/api/reservations'
    | '/api/warehouses'
    | '/checkout/$id'
    | '/api/public/expire-reservations'
    | '/api/reservations/$id'
    | '/api/reservations/$id/confirm'
    | '/api/reservations/$id/release'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  InventoryRoute: typeof InventoryRoute
  ApiProductsRoute: typeof ApiProductsRoute
  ApiReservationsRoute: typeof ApiReservationsRouteWithChildren
  ApiWarehousesRoute: typeof ApiWarehousesRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  ApiPublicExpireReservationsRoute: typeof ApiPublicExpireReservationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/warehouses': {
      id: '/api/warehouses'
      path: '/api/warehouses'
      fullPath: '/api/warehouses'
      preLoaderRoute: typeof ApiWarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reservations': {
      id: '/api/reservations'
      path: '/api/reservations'
      fullPath: '/api/reservations'
      preLoaderRoute: typeof ApiReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reservations/$id': {
      id: '/api/reservations/$id'
      path: '/$id'
      fullPath: '/api/reservations/$id'
      preLoaderRoute: typeof ApiReservationsIdRouteImport
      parentRoute: typeof ApiReservationsRoute
    }
    '/api/public/expire-reservations': {
      id: '/api/public/expire-reservations'
      path: '/api/public/expire-reservations'
      fullPath: '/api/public/expire-reservations'
      preLoaderRoute: typeof ApiPublicExpireReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reservations/$id/release': {
      id: '/api/reservations/$id/release'
      path: '/release'
      fullPath: '/api/reservations/$id/release'
      preLoaderRoute: typeof ApiReservationsIdReleaseRouteImport
      parentRoute: typeof ApiReservationsIdRoute
    }
    '/api/reservations/$id/confirm': {
      id: '/api/reservations/$id/confirm'
      path: '/confirm'
      fullPath: '/api/reservations/$id/confirm'
      preLoaderRoute: typeof ApiReservationsIdConfirmRouteImport
      parentRoute: typeof ApiReservationsIdRoute
    }
  }
}

interface ApiReservationsIdRouteChildren {
  ApiReservationsIdConfirmRoute: typeof ApiReservationsIdConfirmRoute
  ApiReservationsIdReleaseRoute: typeof ApiReservationsIdReleaseRoute
}

const ApiReservationsIdRouteChildren: ApiReservationsIdRouteChildren = {
  ApiReservationsIdConfirmRoute: ApiReservationsIdConfirmRoute,
  ApiReservationsIdReleaseRoute: ApiReservationsIdReleaseRoute,
}

const ApiReservationsIdRouteWithChildren =
  ApiReservationsIdRoute._addFileChildren(ApiReservationsIdRouteChildren)

interface ApiReservationsRouteChildren {
  ApiReservationsIdRoute: typeof ApiReservationsIdRouteWithChildren
}

const ApiReservationsRouteChildren: ApiReservationsRouteChildren = {
  ApiReservationsIdRoute: ApiReservationsIdRouteWithChildren,
}

const ApiReservationsRouteWithChildren = ApiReservationsRoute._addFileChildren(
  ApiReservationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  InventoryRoute: InventoryRoute,
  ApiProductsRoute: ApiProductsRoute,
  ApiReservationsRoute: ApiReservationsRouteWithChildren,
  ApiWarehousesRoute: ApiWarehousesRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  ApiPublicExpireReservationsRoute: ApiPublicExpireReservationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
